[auth]
username = YOUR_USERNAME
password = YOUR_PASSWORD

[feat]
# How many SIMs do you want in a single order? 1 or 3
sims_in_single_order = 3

# How many orders to apply for in total?
# Set to 0 for unlimited until your monthly limit is reached.
total_orders = 0

[dev]
debug = false